#!/usr/bin/env python3
"""test_fistar_cython.py — Cython fistar pipeline validation.
Compares with C binary reference output.
Reference generated by:
  fistar --input L1_GRB260604C-Ic-180s-20260606_210318.fits \\
    -d 5 -f 10000 -s x --format id,ix,iy,...,pl \\
    -g 2 --model gauss --psf native,order=2 \\
    --output L1_GRB260604C-Ic-180s-20260606_210318.cat \\
    --output-psf test.psf.fits
"""
from fitsh_cy import Fistar, Fitrans
from astropy.io import fits
import numpy as np
from scipy.spatial import cKDTree

DATA = '../fitsh_test_data'
REF_CAT = f'{DATA}/L1_GRB260604C-Ic-180s-20260606_210318.cat'
REF_PSF = f'{DATA}/test.psf.fits'
REF_IMG = f'{DATA}/L1_GRB260604C-Ic-180s-20260606_210318.fits'

FMT = ['id','ix','iy','cx','cy','cbg','camp','cmax','npix','cs','cd','ck',
       'x','y','bg','amp','s','d','k','l','sigma','delta','kappa',
       'fwhm','ellip','pa','flux','noise','sn','magnitude',
       'px','py','pbg','pamp','ps','pd','pk','pl']
FIELDS = ','.join(FMT)

# ---- 1. Run Cython ----
print('=== Star detection ===')
img = fits.getdata(REF_IMG).astype(np.float64)
r = Fistar(
    threshold=100.0, flux_threshold=10000.0, skysigma=5.0,
    model='gauss', sort='x',
    psf='native,order=2', psf_output=True, gain=2.0,
    fields=FIELDS, output_mark=True, output_area=True,
).search(img)
tab = r['table']
print(f'  nstar={r["nstar"]}  cols={len(tab.colnames)}')

# ---- 2. Compare catalog ----
print('\n=== Catalog comparison ===')
c_ref = np.loadtxt(REF_CAT)
c_tree = cKDTree(np.column_stack([c_ref[:,FMT.index('x')], c_ref[:,FMT.index('y')]]))
dist, idx = c_tree.query(np.column_stack([tab['x'], tab['y']]))
print(f'  match: max_dist={dist.max():.4f} pix')

diffs = []
for name in FMT:
    if name == 'id' or name == 'mom' or name not in tab.colnames:
        continue
    mx = np.abs(tab[name] - c_ref[:,FMT.index(name)]).max()
    if mx > 0.01:
        diffs.append(f'{name}: max_diff={mx:.2e}')
print(f'  OK: {len(FMT)-2-len(diffs)}/{len(FMT)-2}')
for d in diffs:
    print(f'    {d}')

# ---- 3. Compare PSF ----
print('\n=== PSF comparison ===')
c_psf = fits.getdata(REF_PSF)
cy_psf = r['psf'].data
print(f'  shape: C={c_psf.shape}  Cython={cy_psf.shape}')
all_ok = True
for vi in range(c_psf.shape[0]):
    m = np.abs(c_psf[vi] - cy_psf[vi]).max()
    ok = m < 1e-5
    if not ok: all_ok = False
    print(f'  plane {vi}: max_diff={m:.2e} {"OK" if ok else "FAIL"}')
print(f'  PSF: {"ALL OK" if all_ok else "HAS FAILURES"}')

# ---- 4. output_mark / output_area ----
print('\n=== Mark / Area ===')
print(f'  output_mark: shape={r["output_mark"].shape} mean={r["output_mark"].mean():.3f}')
print(f'  output_area: shape={r["output_area"].shape} nzero={(r["output_area"]==0).sum()}')

print('\n=== ALL TESTS PASSED ===')
